-- Reference schema + security posture for the members table.
--
-- Unlike the other files in this folder, the members table was NOT created by a
-- migration in the repo — it was set up by hand in the Supabase dashboard before
-- these files existed, then extended by the ALTER statements in the other files
-- here. This file documents the resulting table so its shape and — importantly —
-- its row-level-security posture live in the repo rather than only in the
-- dashboard, where they can silently drift.
--
-- members holds PII: name, email, home address, postcode, constituency, and the
-- pledge. Getting its access rules right matters more than for any other table.
--
-- The CREATE TABLE below is a best-effort reconstruction from the other
-- migrations and from buildMemberFields()/the insert in functions/api/pledge.js.
-- It uses IF NOT EXISTS so it is safe (a no-op) against the live table.
--
-- `id` is confirmed BIGINT in production (Supabase's default identity column
-- when a table is created via the dashboard, not UUID) — found the hard way
-- when supabase/member_sessions.sql's foreign key to members(id) failed with
-- "incompatible types: uuid and bigint". Every other table in this repo that
-- references members(id) (member_login_sessions, member_submissions) must use
-- BIGINT for member_id, not UUID. `created_at`'s type is still unconfirmed.

CREATE TABLE IF NOT EXISTS members (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- confirmed bigint in prod; identity clause is our best guess at how it's populated
  first_name      TEXT        NOT NULL,
  last_name       TEXT        NOT NULL,
  email           TEXT,
  email_canonical TEXT,                    -- normalised email; unique index below (see email_canonical.sql)
  pledge_level    TEXT,
  contact_pref    TEXT,
  address_line1   TEXT,                    -- nullable: constituency-only signups carry no address (see nullable_address.sql)
  address_line2   TEXT,
  city            TEXT,
  postcode        TEXT,
  constituency    TEXT,
  pledge_signed   BOOLEAN,
  signed_at       TIMESTAMPTZ,
  -- Double opt-in email confirmation (see email_confirmation.sql):
  confirmed       BOOLEAN     NOT NULL DEFAULT TRUE,
  confirmed_at    TIMESTAMPTZ,
  confirm_token   TEXT,
  confirm_sent_at TIMESTAMPTZ,
  -- Staged "edit your details" payload applied by /api/confirm (see pending_update.sql):
  pending_update  JSONB,
  created_at      TIMESTAMPTZ DEFAULT NOW()  -- confirm existence/type against prod
);

-- One member per canonical inbox (see supabase/email_canonical.sql).
CREATE UNIQUE INDEX IF NOT EXISTS members_email_canonical_key ON members (email_canonical);
CREATE INDEX IF NOT EXISTS members_confirm_token_idx ON members (confirm_token);

-- ── Row Level Security ────────────────────────────────────────────────────────
-- INTENDED POSTURE: RLS ON, and NO policies for anon/public — zero policies at
-- all. Every read and write of members happens in the Cloudflare Functions with
-- the SERVICE-ROLE key (see pledge.js, latest-member.js, member-details.js),
-- which bypasses RLS entirely. The site never reads or writes members with the
-- anon key. So the anon/public role needs no access, and granting it any is a
-- data-exposure risk:
--   • a SELECT policy for anon/public would let anyone holding the (semi-public)
--     project URL + anon key dump the entire PII roster;
--   • an INSERT policy for anon/public would let anyone write arbitrary rows
--     straight into the table, bypassing all validation, de-duplication, rate
--     limiting and email confirmation in pledge.js.
-- A prior "Allow public insert" (FOR INSERT TO public) policy was found and
-- dropped for exactly this reason.
--
-- Contrast with mp_ratings (supabase/mp_ratings.sql), which DOES grant anon
-- SELECT because grades are public and the site build reads them with the anon
-- key. members is the opposite: nothing public should ever read or write it.
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert" ON members;

-- Verify the posture at any time in the Supabase SQL editor:
--   select relname, relrowsecurity from pg_class where relname = 'members';
--     -> expect relrowsecurity = true
--   select * from pg_policies where tablename = 'members';
--     -> expect zero rows
